tracker_type: botsort

track_high_thresh: 0.40
track_low_thresh: 0.10
new_track_thresh: 0.45

track_buffer: 60
match_thresh: 0.85

fuse_score: True
gmc_method: sparseOptFlow

proximity_thresh: 0.5
appearance_thresh: 0.8

with_reid: False
model: auto
